---
- name: Install elasticsearch
  hosts: elasticsearch
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install gnupg, apt-transport-https
      apt:
        name:
          - apt-transport-https
          - gnupg
        state: present

    - name: Get elasticsearch 7.4.1
      ansible.builtin.get_url:
        url: "https://mirror.yandex.ru/mirrors/elastic/7/pool/main/e/elasticsearch/elasticsearch-7.4.1-amd64.deb"
        dest: /home/ubuntu/

    - name: Install elasticsearch
      apt:
        deb: /home/ubuntu/elasticsearch-7.4.1-amd64.deb

    - name: Systemctl daemon reload
      systemd:
        daemon_reload: true
        name: elasticsearch.service
        state: started

    - name: Copy config file for elasticsearch
      copy:
        src: /home/ubuntu/ansible/elk-configs/elasticsearch.yml
        dest: /etc/elasticsearch
        mode: 0660
        owner: root
        group: elasticsearch

    - name: Systemctl enable elasticsearch
      systemd:
        name: elasticsearch.service
        state: restarted